# Generated by Django 2.2 on 2019-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=10)),
                ('userPassword', models.CharField(max_length=40)),
                ('idDelete', models.BooleanField()),
            ],
        ),
    ]
