# Generated by Django 2.2 on 2019-04-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='idDelete',
        ),
    ]
