# Generated by Django 2.2 on 2019-04-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpApp', '0002_remove_userinfo_iddelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='idDelete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
