# Generated by Django 2.2 on 2019-04-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpApp', '0003_userinfo_iddelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='idCommit',
            field=models.BigIntegerField(default=0),
        ),
    ]
