# Generated by Django 2.2 on 2019-04-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpApp', '0004_userinfo_idcommit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='idCommit',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='idDelete',
        ),
    ]
