# Generated by Django 2.2 on 2019-04-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpApp', '0005_auto_20190429_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='idDelete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
